name: Build Custom package

on:
  workflow_dispatch:
  push:
    paths:
      - 'srcpkgs/**'

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: 'ghcr.io/void-linux/xbps-src-masterdir:latest-${{ matrix.config.bootstrap }}'
      env:
        PATH: '/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/sbin:/usr/local/bin:/tmp/bin'
        ARCH: '${{ matrix.config.arch }}'
        BOOTSTRAP: '${{ matrix.config.bootstrap }}'
        # TEST: '${{ matrix.config.test }}'
        HOSTREPO: /hostrepo
        REPO_URL: ${{github.server_url}}/${{github.repository}}
        REPOSITORY: '${{ github.repository }}'
        BRANCH: '${{ github.ref_name }}'
        REF: '${{ github.ref }}'

    strategy:
      fail-fast: false
      matrix:
        config:
          - { arch: x86_64, bootstrap: x86_64, test: 1 }
          # - { arch: i686, bootstrap: i686, test: 1 }
          # - { arch: aarch64, bootstrap: x86_64, test: 0 }
          # - { arch: armv7l, bootstrap: x86_64, test: 0 }
          # - { arch: x86_64-musl, bootstrap: x86_64-musl, test: 1 }
          # - { arch: armv6l-musl, bootstrap: x86_64-musl, test: 0 }
          # - { arch: aarch64-musl, bootstrap: x86_64-musl, test: 0 }

    steps:
      - name: Prepare container
        run: |
          # switch to repo-ci mirror
          mkdir -p /etc/xbps.d && cp /usr/share/xbps.d/*-repository-*.conf /etc/xbps.d/
          sed -i 's|repo-default|repo-ci|g' /etc/xbps.d/*-repository-*.conf
          # Sync and upgrade once, assume error comes from xbps update
          xbps-install -Syu || xbps-install -yu xbps
          # Upgrade again (in case there was a xbps update)
          xbps-install -yu
          # install tools needed for lints
          xbps-install -y grep curl git

      # Non x86_64: https://github.com/actions/checkout/issues/334
      - uses: actions/checkout@v4
        with:
          fetch-depth: 201

      - name: Create hostrepo and prepare masterdir
        run: |
          ln -s "$(pwd)" /hostrepo \
          && common/travis/set_mirror.sh \
          && common/travis/prepare.sh \
          && git config --global --add safe.directory "$(pwd)" \
          && common/travis/fetch-xtools.sh

      - name: Adding upstream and get changed packages
        run: |
          cd /__w/void-packages/void-packages/ && \
          git config --global --add safe.directory /__w/void-packages/void-packages && \
          git remote add upstream https://github.com/void-linux/void-packages && \
          git fetch upstream master && \

          common/travis/changed_templates.sh

      - name: Github ci package include and exclude
        run: |
          cat .github-actions-include.txt >> /tmp/templates
          grep -vxFf .github-actions-exclude.txt /tmp/templates > /tmp/templates.tmp \
          && mv /tmp/templates.tmp /tmp/templates

      - name: Checking build packages
        run: |
          cat /tmp/templates

      - name: Build (xbps-src)
        run: |
          here="$(pwd)"
          cd /
          echo; echo "===== Building Packages ====="
          "$here/common/travis/build.sh" "$BOOTSTRAP" "$ARCH" "$TEST"
          cd -

      - name: Metadata and Verification (void-packages/scripts)
        run: |
          here="$(pwd)"
          cd /
          echo; echo "===== Displaying Files ====="
          "$here/common/travis/show_files.sh" "$BOOTSTRAP" "$ARCH"
          echo; echo "===== Displaying Diffs ====="
          "$here/common/travis/xpkgdiff.sh" "$BOOTSTRAP" "$ARCH"
          echo; echo "===== Checking installation ====="
          "$here/common/travis/check-install.sh" "$BOOTSTRAP" "$ARCH"
          cd -

      - name: Sign repository
        run: |
          echo "${{ secrets.SIGNING_RSA_KEY }}" > private.pem
          xbps-rindex --privkey private.pem --sign --signedby "Aditya Yadav" $HOME/hostdir/binpkgs
          xbps-rindex --privkey private.pem --sign-pkg $HOME/hostdir/binpkgs/*.xbps

      - name: Remove files larger than 100MB
        run: |
          cd $HOME/hostdir/binpkgs && \
          find . -type f -size +100M -exec rm -f {} +

      - name: Deploy
        run: |
          cd $HOME/hostdir/binpkgs && \
          git config --global user.name 'github-actions[bot]' && \
          git config --global user.email 'github-actions[bot]@users.noreply.github.com' && \
          # Error fix: https://stackoverflow.com/questions/62753648/rpc-failed-http-400-curl-22-the-requested-url-returned-error-400-bad-request
          git config --global http.postBuffer 1048576000 && \
          git init . -b binaries && \
          git add . && \
          git commit --no-verify --signoff --author "${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>" -m "Deploy XBPS Binaries"
          git push -fu "https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY" HEAD:binaries --atomic
